name: action
on:
  schedule:
    # Runs every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  action:
    name: Fetch repo data and generate readme file
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
      - uses: actions/checkout@v2
      - name: Set up NodeJs
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
      - run: npm ci
      - name: Run main script
        env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - run: npm start || exit 0